### ISSUE TITLE
Invalid MEX-file

### ISSUE THREAD

**Issue by xucao-42** [BjoernHaefner/DepthSRfromShading#1]
When I run the main.m in **MATLAB R2017a on Ubuntu16.04**., it throws following error messages:

> Invalid MEX-file
> '/home/hoshino/Documents/DepthSRfromShading/third_party/mumfordshah/MumfordShahCuda/build/lib/mumfordShahMEX.mexa64':
> Missing symbol '_Z18StoreArrayAsBinaryIfEbRKSsPKT_RKmS6_S6_' required by
> '/home/hoshino/Documents/DepthSRfromShading/third_party/mumfordshah/MumfordShahCuda/build/lib/mumfordShahMEX.mexa64'
> Missing symbol '_ZN4CUDA6norm2DIfEET_PKS1_iiNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'
> required by
> '/home/hoshino/Documents/DepthSRfromShading/third_party/mumfordshah/MumfordShahCuda/build/lib/mumfordShahMEX.mexa64'
> Missing symbol '_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5c_strEv' required by
> '/home/hoshino/Documents/DepthSRfromShading/third_party/mumfordshah/MumfordShahCuda/build/lib/mumfordShahMEX.mexa64'
> Missing symbol '_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5emptyEv' required by
> '/home/hoshino/Documents/DepthSRfromShading/third_party/mumfordshah/MumfordShahCuda/build/lib/mumfordShahMEX.mexa64'
> Missing symbol '_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc' required by
> '/home/hoshino/Documents/DepthSRfromShading/third_party/mumfordshah/MumfordShahCuda/build/lib/mumfordShahMEX.mexa64'
> Missing symbol '_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareERKS4_' required by
> '/home/hoshino/Documents/DepthSRfromShading/third_party/mumfordshah/MumfordShahCuda/build/lib/mumfordShahMEX.mexa64'
> Missing symbol '_ZNKSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEE3strEv' required by
> '/home/hoshino/Documents/DepthSRfromShading/third_party/mumfordshah/MumfordShahCuda/build/lib/mumfordShahMEX.mexa64'
> Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEaSEOS4_' required by
> '/home/hoshino/Documents/DepthSRfromShading/third_party/mumfordshah/MumfordShahCuda/build/lib/mumfordShahMEX.mexa64'
> Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EPKcRKS3_' required by
> '/home/hoshino/Documents/DepthSRfromShading/third_party/mumfordshah/MumfordShahCuda/build/lib/mumfordShahMEX.mexa64'
> Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1ERKS4_' required by
> '/home/hoshino/Documents/DepthSRfromShading/third_party/mumfordshah/MumfordShahCuda/build/lib/mumfordShahMEX.mexa64'
> Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1Ev' required by
> '/home/hoshino/Documents/DepthSRfromShading/third_party/mumfordshah/MumfordShahCuda/build/lib/mumfordShahMEX.mexa64'
> Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev' required by
> '/home/hoshino/Documents/DepthSRfromShading/third_party/mumfordshah/MumfordShahCuda/build/lib/mumfordShahMEX.mexa64'
> Missing symbol '_ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1ESt13_Ios_Openmode'
> required by
> '/home/hoshino/Documents/DepthSRfromShading/third_party/mumfordshah/MumfordShahCuda/build/lib/mumfordShahMEX.mexa64'
> Missing symbol '_ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEED1Ev' required by
> '/home/hoshino/Documents/DepthSRfromShading/third_party/mumfordshah/MumfordShahCuda/build/lib/mumfordShahMEX.mexa64'
> Missing symbol
> '_ZStlsIcSt11char_traitsIcESaIcEERSt13basic_ostreamIT_T0_ES7_RKNSt7__cxx1112basic_stringIS4_S5_T1_EE'
> required by
> '/home/hoshino/Documents/DepthSRfromShading/third_party/mumfordshah/MumfordShahCuda/build/lib/mumfordShahMEX.mexa64'.
> 
> Error in depthSRfromShading (line 221)
>   ms = mumfordShahMEX('initMumfordShah', params.lambda/params.gamma, options.PD.alpha,
>   options.PD.maxIter, options.PD.tol, options.PD.gamma, options.PD.verbose, options.PD.tau,
>   options.PD.sigma);
> 
> Error in main (line 113)
> [z_est, albedo_est, l_est] = depthSRfromShading(I_noise, z0_noise, mask_sr, K_sr, params, options);

Mumfordshah is built with **gcc4.9**, and the settings in CMakeLists.txt is: 

> #what shall be build?
> SET(MEXF TRUE) #generate mex file for matlab usage
> SET(EXEF FALSE) #generate executable to call code from commandline
> SET(CUDA TRUE) #use cuda for speedup if applicable
> SET(DEBUG FALSE) #to debug gpu code in NSight

Do you have any ideas?

**Comment by BjoernHaefner** [comment]
Did you link to the correct matlab binary? Meaning, did you add `export MATLAB_ROOT='/path/to/MATLAB/matlab-R2017a` to your `.bashrc`?

Did you try to run the mumfordshah examples or did you try to run the mumfordshah code without gpu support?
